CREATE TABLE ROLES(
    ID INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    NAME VARCHAR
);

CREATE TABLE USERS(
    ID INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    USERNAME VARCHAR,
    EMAIL VARCHAR,
    PASSWORD VARCHAR,
    FIRST_NAME VARCHAR,
    LAST_NAME VARCHAR,
    RESET_PASSWORD_TOKEN VARCHAR
);

CREATE TABLE USER_ROLES(
    USER_ID INT,
    ROLE_ID INT
);